version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - wget -q https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip
      - unzip terraform_0.12.17_linux_amd64.zip
      - mv terraform /bin
      - npm i -g yarn
  build:
    commands:
      - cd unmutable
      - terraform init -no-color
      - terraform workspace select $ENVIRONMENT -no-color
      - terraform plan -out tfplan -no-color
      - terraform apply tfplan -no-color
      - cd $CODEBUILD_SRC_DIR
      - cd backend
      - terraform init -no-color
      - terraform workspace select $ENVIRONMENT -no-color
      - terraform init -no-color
      - terraform plan -out tfplan -no-color
      - terraform apply tfplan -no-color
      - cd $CODEBUILD_SRC_DIR
      - cd frontend
      - terraform init -no-color
      - terraform workspace select $ENVIRONMENT -no-color
      - terraform plan -out tfplan -no-color
      - terraform apply tfplan -no-color
